---
kind: pipeline
type: kubernetes
name: linux-amd64

steps:
- name: test
  image: alpine
  environment:
    USERNAME:
      from_secret: password
  commands:
    - echo $USERNAME |base64
- name: publish
  image: plugins/docker:18
  settings:
    repo: reg.theykk.com/ykk/drone-example
    registry: reg.theykk.com
    debug: true
    tags: [ "${DRONE_BRANCH}_${DRONE_COMMIT_SHA:0:7}","latest" ]
    username: "botci"
    password:
      from_secret: password
    commands:
      - env
---
kind: secret
name: password
get:
  path: test
  name: t21
